/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ConnectionInput {
  pre: string
  post: string
  weight?: number
}
export interface FlyInput {
  x: number
  y: number
  z: number
  heading: number
  t: number
  hunger: number
  health: number
  restTimeLeft: number
}
export interface SourceInput {
  x: number
  y: number
  radius: number
}
export interface PendingStimInput {
  neuronIds: Array<string>
  strength: number
}
export interface StepResult {
  activity: Float32Array
  motorLeft: number
  motorRight: number
  motorFwd: number
}
/**
 * Adjacency: for each pre_idx, list of (post_idx, weight).
 * id_to_idx: neuron root_id -> index
 */
export declare class BrainSim {
  constructor(neuronIds: Array<string>, connections: Array<ConnectionInput>, sensoryIndices: Array<number>, motorLeft: Array<number>, motorRight: Array<number>, motorUnknown: Array<number>)
  step(dt: number, fly: FlyInput, sources: Array<SourceInput>, pending: Array<PendingStimInput>): StepResult
  getActivity(): Float32Array
  get isUsingGpu(): boolean
}
